### ISSUE TITLE
Add support for debug and optimized PXB during PTB run

### ISSUE THREAD

**Issue by ShahriyarR** [Percona-QA/PTB#22]
The idea is, to compile from source PXB during PTB run.
It will be great to have this inside Jenkins job.
The same test should be run, using Debug and Optimized PXB.
- `cmake -DWITH_DEBUG=1 -DBUILD_CONFIG=xtrabackup_release -DWITH_MAN_PAGES=OFF -DDOWNLOAD_BOOST=1 -DWITH_BOOST=/opt/boost/ && make -j2`
- `cmake -DBUILD_CONFIG=xtrabackup_release -DWITH_MAN_PAGES=OFF -DDOWNLOAD_BOOST=1 -DWITH_BOOST=/opt/boost/ && make -j2`

Default path will be -> _/usr/local/xtrabackup/_

**Comment by ShahriyarR** [comment]
Implemented. Thanks @rameshvs02 for help :)

**Comment by RoelVdP** [comment]
@ShahriyarR what is/are the Jenkins URL(s)?

**Comment by ShahriyarR** [comment]
@RoelVdP:

PXB-2.4 : http://jenkins.percona.com/view/QA/job/qa.pxb24.clone/
PXB-2.3 : http://jenkins.percona.com/view/QA/job/qa.pxb23.clone/
it will initiate PXB build jobs and then you can run PTB job

http://jenkins.percona.com/view/QA/job/qa.pxb24.clone/  will initiate http://jenkins.percona.com/view/QA/job/qa.pxb24.build/

same for PXB-2.3
http://jenkins.percona.com/view/QA/job/qa.pxb23.clone/ will initiate http://jenkins.percona.com/view/QA/job/qa.pxb23.build/

Once these jobs finished please execute : http://jenkins.percona.com/job/PTB-run-percona-server-5.6-pxb-2.3.5-2.4.4/

**Comment by ShahriyarR** [comment]
Already implemented. Closing.
