### ISSUE TITLE
Add support for tablespace encryption; start server with keyring plugin; update PXB commands

### ISSUE THREAD

**Issue by ShahriyarR** [Percona-QA/PTB#26]
For 5.7 server, it should be started with encryption, i.e

1.  Start server with tablespace encryption enabled.

2.  Alter sysbench tables to use encryption.

3.  Add proper PXB commands for taking and preparing backups with encryption key.

**Comment by RoelVdP** [comment]
As before, would recommend only encrypting part of the tables, say 20%, and not all of them.

**Comment by ShahriyarR** [comment]
Implemented. Closing.
