### ISSUE TITLE
Jenkins job failed with; /bin/mysqld: No such file or directory

### ISSUE THREAD

**Issue by ShahriyarR** [Percona-QA/PTB#30]
From console output:

```
20:21:34 2016/11/13 20:21:34.138662875 13945 INFO : main() - Starting test 0 with [innodb_checksums=ON log-bin-index= binlog-format=row log-bin= innodb_flush_log_at_trx_commit=1 innodb_file_per_table=1 innodb_file_format=antelope innodb_flush_method=O_DIRECT innodb_log_file_size=1G innodb_buffer_pool_size=1G ] and [parallel=1 ]
20:25:20 ./include/sysbench_oltp_prepare.sh: line 131: /bin/mysqld: No such file or directory
20:25:20 ./include/sysbench_oltp_prepare.sh: line 131: [: ==: unary operator expected
20:25:20 ./include/sysbench_oltp_prepare.sh: line 165: /bin/mysqld: No such file or directory
20:25:20 ./include/sysbench_oltp_prepare.sh: line 165: [: ==: unary operator expected
```

**Comment by RoelVdP** [comment]
[: ==: unary operator expected is likely due to not enclosing variables, i.e. 

if [ $1 == "a" ]; then

where $1 was never set. Can be avoided by enclosing $1;

if [ "$1" == "a" ]; then

**Comment by ShahriyarR** [comment]
Right, it seems to be that I have passed wrong server_id.
if [ $(${S_BINDIR[$PTB_OPT_server_id]}/bin/mysqld --version | grep -oe '5.[567]' | head -n1) == "5.6" ]; 
Now it works.

**Comment by RoelVdP** [comment]
yeah so this would become something like

if [ "$(${S_BINDIR[$PTB_OPT_server_id]}/bin/mysqld --version | grep -oe '5.[567]' | head -n1)" == "5.6" ];
